export const PRESET_EXERCISES = {
  chest: [
    'Barbell Bench Press',
    'Dumbbell Bench Press',
    'Incline Barbell Press',
    'Incline Dumbbell Press',
    'Decline Bench Press',
    'Machine Chest Press',
    'Cable Chest Press',
    'Chest Fly Machine',
    'Dumbbell Fly',
    'Cable Fly',
    'Push-ups',
    'Dips (Chest)',
  ],
  back: [
    'Deadlift',
    'Sumo Deadlift',
    'Romanian Deadlift (RDL)',
    'Barbell Rows',
    'Dumbbell Rows',
    'Machine Rows',
    'Lat Pulldown',
    'Pull-ups',
    'Assisted Pull-ups',
    'Chin-ups',
    'Pendulum Rows',
    'T-Bar Rows',
    'Bent-Over Barbell Rows',
    'Seal Rows',
    'Chest-Supported Rows',
    'Face Pulls',
    'Shrugs',
    'Smith Machine Rows',
  ],
  shoulders: [
    'Barbell Shoulder Press',
    'Dumbbell Shoulder Press',
    'Machine Shoulder Press',
    'Lateral Raises',
    'Dumbbell Lateral Raises',
    'Cable Lateral Raises',
    'Front Raises',
    'Reverse Fly',
    'Reverse Pec Deck',
    'Overhead Press',
    'Military Press',
    'Pike Push-ups',
    'Upright Rows',
  ],
  biceps: [
    'Barbell Curls',
    'Dumbbell Curls',
    'Machine Curls',
    'Cable Curls',
    'EZ-Bar Curls',
    'Incline Dumbbell Curls',
    'Preacher Curls',
    'Hammer Curls',
    'Cable Hammer Curls',
    'Concentration Curls',
    '21s Curls',
  ],
  triceps: [
    'Tricep Dips',
    'Rope Pushdowns',
    'V-Bar Pushdowns',
    'Straight Bar Pushdowns',
    'Tricep Overhead Extensions',
    'EZ-Bar Overhead Extensions',
    'Skull Crushers',
    'Dumbbell Overhead Extensions',
    'Close-Grip Bench Press',
    'Tricep Kickbacks',
    'Machine Tricep Dips',
  ],
  forearms: [
    'Barbell Wrist Curls',
    'Dumbbell Wrist Curls',
    'Wrist Curls Machine',
    'Reverse Wrist Curls',
    'Farmer Walks',
    'Farmer Carries',
  ],
  legs: [
    'Barbell Squats',
    'Dumbbell Squats',
    'Leg Press Machine',
    'Smith Machine Squats',
    'Bulgarian Split Squats',
    'Goblet Squats',
    'Hack Squats',
    'Leg Extensions',
    'Leg Curls (Lying)',
    'Leg Curls (Seated)',
    'Walking Lunges',
    'Dumbbell Lunges',
    'Barbell Lunges',
    'Reverse Lunges',
    'Step-ups',
    'Wall Sits',
  ],
  calves: [
    'Standing Calf Raises',
    'Seated Calf Raises',
    'Machine Calf Raises',
    'Calf Raises on Leg Press',
    'Donkey Calf Raises',
  ],
  core: [
    'Barbell Abs Rollouts',
    'Ab Wheel Rollouts',
    'Cable Crunches',
    'Machine Crunches',
    'Decline Sit-ups',
    'Rope Crunches',
    'Leg Raises',
    'Hanging Leg Raises',
    'Hanging Knee Raises',
    'Dragon Flags',
    'Planks',
    'Side Planks',
    'Ab Wheel',
    'Torso Rotation Machine',
  ],
};

export function getAllExercises() {
  const exercises = [];
  for (const [muscleGroup, names] of Object.entries(PRESET_EXERCISES)) {
    for (const name of names) {
      exercises.push({ name, muscleGroup });
    }
  }
  return exercises;
}

export function getExercisesByMuscle(muscleGroup: string) {
  return PRESET_EXERCISES[muscleGroup as keyof typeof PRESET_EXERCISES] || [];
}
