// Translates the French coach notes (EXERCISE_INFO) to EN/ES on the fly using
// regex substitutions for common gym verbs and nouns. Not perfect — covers
// ~70% of the text — but readable and runs offline. For higher quality the
// Gemini-based translateExerciseSteps could be plugged in later.

import { getLang } from './i18n';

type Phrase = [RegExp, string];

const FR_EN: Phrase[] = [
  // Pronouns / connectors
  [/\bAllongé sur un banc\b/gi, 'Lying on a bench'],
  [/\bDescend\b/gi, 'Lower the weight'],
  [/\bDescends\b/gi, 'Lower'],
  [/\bMonte\b/gi, 'Push up'],
  [/\bRemonte\b/gi, 'Push back up'],
  [/\bTu te penches\b/gi, 'Lean'],
  [/\bTu pousses\b/gi, 'Push'],
  [/\bTu fléchis\b/gi, 'Bend'],
  [/\bTu tires\b/gi, 'Pull'],
  [/\bTu ramènes\b/gi, 'Bring back'],
  [/\bTu remontes\b/gi, 'Lift'],
  [/\bGarde\b/gi, 'Keep'],
  [/\bSent\b/gi, 'Feel'],
  [/\bNote\b/gi, 'Track'],
  [/\bvise\b/gi, 'aim to'],
  [/\bprogresser\b/gi, 'progress'],
  [/\bsemaine après semaine\b/gi, 'week after week'],
  // Anatomy
  [/\bpectoraux?\b/gi, 'chest'],
  [/\bpecs\b/gi, 'chest'],
  [/\bdeltoïdes? antérieurs?\b/gi, 'front delts'],
  [/\bdeltoïdes? médians?\b/gi, 'side delts'],
  [/\bdeltoïdes? postérieurs?\b/gi, 'rear delts'],
  [/\bcoiffe des rotateurs\b/gi, 'rotator cuff'],
  [/\bgrand dorsal\b/gi, 'lats'],
  [/\bbiceps\b/gi, 'biceps'],
  [/\btriceps\b/gi, 'triceps'],
  [/\blong chef du triceps\b/gi, 'long head of the triceps'],
  [/\bbrachial antérieur\b/gi, 'brachialis'],
  [/\bavant-bras\b/gi, 'forearms'],
  [/\brhomboïdes\b/gi, 'rhomboids'],
  [/\btrapèze moyen\b/gi, 'mid traps'],
  [/\bomoplates?\b/gi, 'shoulder blades'],
  [/\bcoudes?\b/gi, 'elbows'],
  [/\bgenoux?\b/gi, 'knees'],
  [/\bpoitrine\b/gi, 'chest'],
  [/\bventre\b/gi, 'core'],
  [/\bvisage\b/gi, 'face'],
  [/\bdos\b/gi, 'back'],
  [/\bbras\b/gi, 'arm'],
  [/\bcuisses?\b/gi, 'thighs'],
  [/\bhanches?\b/gi, 'hips'],
  [/\bfront\b/gi, 'forehead'],
  // Equipment
  [/\bbarbell?\b/gi, 'barbell'],
  [/\bsmith machine\b/gi, 'Smith machine'],
  [/\bpoulie haute\b/gi, 'high pulley'],
  [/\bpoulie basse\b/gi, 'low pulley'],
  [/\bpoulie\b/gi, 'pulley'],
  [/\bcâble\b/gi, 'cable'],
  [/\bbarre EZ\b/gi, 'EZ bar'],
  [/\bdumbbell?\b/gi, 'dumbbell'],
  [/\bbanc horizontal\b/gi, 'flat bench'],
  [/\bbanc incliné\b/gi, 'incline bench'],
  [/\bbanc\b/gi, 'bench'],
  [/\bcorde à 2 têtes\b/gi, 'rope attachment'],
  [/\bcorde\b/gi, 'rope'],
  [/\bmachine\b/gi, 'machine'],
  [/\brails fixes\b/gi, 'fixed rails'],
  // Position / motion
  [/\bprise pronation\b/gi, 'overhand grip'],
  [/\bprise supination\b/gi, 'underhand grip'],
  [/\bprise neutre\b/gi, 'neutral grip'],
  [/\bprise marteau\b/gi, 'hammer grip'],
  [/\bprise large\b/gi, 'wide grip'],
  [/\bprise\b/gi, 'grip'],
  [/\bpaumes vers l'avant\b/gi, 'palms forward'],
  [/\bpaumes face à face\b/gi, 'palms facing each other'],
  [/\bpaumes vers le sol\b/gi, 'palms down'],
  [/\bvers le bas\b/gi, 'down'],
  [/\bvers le haut\b/gi, 'up'],
  [/\bvers l'avant\b/gi, 'forward'],
  [/\bvers l'arrière\b/gi, 'backward'],
  [/\ben arc de cercle\b/gi, 'in an arc'],
  [/\ben fin de mouvement\b/gi, 'at the end of the rep'],
  [/\bbras tendus?\b/gi, 'arms extended'],
  [/\blégère flexion coude\b/gi, 'slight elbow bend'],
  [/\bcoudes hauts\b/gi, 'elbows high'],
  [/\bcoudes collés au corps\b/gi, 'elbows tucked'],
  [/\bsécurité solo\b/gi, 'solo safety'],
  [/\bétirement maximal\b/gi, 'maximum stretch'],
  [/\bétirement complet\b/gi, 'full stretch'],
  [/\bextension complète\b/gi, 'full extension'],
  [/\btempo lent\b/gi, 'slow tempo'],
  [/\bsans élan\b/gi, 'no momentum'],
  [/\bisolation pure\b/gi, 'pure isolation'],
  [/\bsans tricher\b/gi, 'without cheating'],
  // Common phrases
  [/\blargeur d'épaules\b/gi, 'shoulder-width'],
  [/\blégèrement plus large que les épaules\b/gi, 'slightly wider than shoulder-width'],
  [/\bau-dessus de la tête\b/gi, 'overhead'],
  [/\bdans chaque bloc\b/gi, 'each block'],
  [/\bmax reps\b/gi, 'max reps'],
  [/\b15 sec repos\b/gi, '15 sec rest'],
  [/\b2-3 min de repos\b/gi, '2-3 min rest'],
  [/\bréglées?\b/gi, 'set'],
  [/\bderrière toi\b/gi, 'behind you'],
  [/\bdans ton ventre\b/gi, 'to your stomach'],
  [/\bvers ton visage\b/gi, 'toward your face'],
  [/\bvers le front\b/gi, 'toward your forehead'],
  [/\bessentielle? pour la santé\b/gi, 'essential for the health'],
  [/\bExcellent finisher\b/gi, 'Great finisher'],
  [/\baspect bombé\b/gi, 'bulky look'],
  [/\bdonne le relief\b/gi, 'shapes the upper'],
  [/\bdonne du volume\b/gi, 'adds volume'],
  [/\bsans douleur aux poignets\b/gi, 'with no wrist pain'],
  [/\bcontrôlant\b/gi, 'control'],
  // Articles
  [/\bUNIQUEMENT\b/g, 'ONLY'],
  [/\bÉCARTANT\b/g, 'SPREADING'],
  [/\bVERS LES HANCHES\b/g, 'TOWARD THE HIPS'],
  [/\bLE muscle\b/g, 'THE muscle'],
];

const FR_ES: Phrase[] = [
  [/\bAllongé sur un banc\b/gi, 'Tumbado en un banco'],
  [/\bDescend\b/gi, 'Baja'],
  [/\bDescends\b/gi, 'Baja'],
  [/\bMonte\b/gi, 'Sube'],
  [/\bRemonte\b/gi, 'Vuelve a subir'],
  [/\bTu te penches\b/gi, 'Inclínate'],
  [/\bTu pousses\b/gi, 'Empuja'],
  [/\bTu fléchis\b/gi, 'Flexiona'],
  [/\bTu tires\b/gi, 'Tira'],
  [/\bTu ramènes\b/gi, 'Lleva'],
  [/\bTu remontes\b/gi, 'Sube'],
  [/\bGarde\b/gi, 'Mantén'],
  [/\bSent\b/gi, 'Siente'],
  [/\bNote\b/gi, 'Anota'],
  [/\bvise\b/gi, 'apunta a'],
  [/\bprogresser\b/gi, 'progresar'],
  [/\bsemaine après semaine\b/gi, 'semana tras semana'],
  [/\bpectoraux?\b/gi, 'pectorales'],
  [/\bpecs\b/gi, 'pecho'],
  [/\bdeltoïdes? antérieurs?\b/gi, 'deltoides anteriores'],
  [/\bdeltoïdes? médians?\b/gi, 'deltoides medios'],
  [/\bdeltoïdes? postérieurs?\b/gi, 'deltoides posteriores'],
  [/\bcoiffe des rotateurs\b/gi, 'manguito rotador'],
  [/\bgrand dorsal\b/gi, 'dorsal'],
  [/\bbiceps\b/gi, 'bíceps'],
  [/\btriceps\b/gi, 'tríceps'],
  [/\blong chef du triceps\b/gi, 'cabeza larga del tríceps'],
  [/\bbrachial antérieur\b/gi, 'braquial'],
  [/\bavant-bras\b/gi, 'antebrazos'],
  [/\brhomboïdes\b/gi, 'romboides'],
  [/\btrapèze moyen\b/gi, 'trapecio medio'],
  [/\bomoplates?\b/gi, 'escápulas'],
  [/\bcoudes?\b/gi, 'codos'],
  [/\bgenoux?\b/gi, 'rodillas'],
  [/\bpoitrine\b/gi, 'pecho'],
  [/\bventre\b/gi, 'vientre'],
  [/\bvisage\b/gi, 'cara'],
  [/\bdos\b/gi, 'espalda'],
  [/\bbras\b/gi, 'brazo'],
  [/\bcuisses?\b/gi, 'muslos'],
  [/\bhanches?\b/gi, 'caderas'],
  [/\bfront\b/gi, 'frente'],
  [/\bsmith machine\b/gi, 'máquina Smith'],
  [/\bpoulie haute\b/gi, 'polea alta'],
  [/\bpoulie basse\b/gi, 'polea baja'],
  [/\bpoulie\b/gi, 'polea'],
  [/\bcâble\b/gi, 'cable'],
  [/\bbarre EZ\b/gi, 'barra Z'],
  [/\bbanc horizontal\b/gi, 'banco plano'],
  [/\bbanc incliné\b/gi, 'banco inclinado'],
  [/\bbanc\b/gi, 'banco'],
  [/\bcorde à 2 têtes\b/gi, 'cuerda doble'],
  [/\bcorde\b/gi, 'cuerda'],
  [/\bmachine\b/gi, 'máquina'],
  [/\brails fixes\b/gi, 'rieles fijos'],
  [/\bprise pronation\b/gi, 'agarre prono'],
  [/\bprise supination\b/gi, 'agarre supino'],
  [/\bprise neutre\b/gi, 'agarre neutro'],
  [/\bprise marteau\b/gi, 'agarre martillo'],
  [/\bprise large\b/gi, 'agarre amplio'],
  [/\bprise\b/gi, 'agarre'],
  [/\bpaumes vers l'avant\b/gi, 'palmas al frente'],
  [/\bpaumes face à face\b/gi, 'palmas enfrentadas'],
  [/\bpaumes vers le sol\b/gi, 'palmas abajo'],
  [/\bvers le bas\b/gi, 'hacia abajo'],
  [/\bvers le haut\b/gi, 'hacia arriba'],
  [/\bvers l'avant\b/gi, 'hacia adelante'],
  [/\bvers l'arrière\b/gi, 'hacia atrás'],
  [/\ben arc de cercle\b/gi, 'en arco'],
  [/\ben fin de mouvement\b/gi, 'al final del movimiento'],
  [/\bbras tendus?\b/gi, 'brazos extendidos'],
  [/\blégère flexion coude\b/gi, 'leve flexión del codo'],
  [/\bcoudes hauts\b/gi, 'codos altos'],
  [/\bcoudes collés au corps\b/gi, 'codos pegados al cuerpo'],
  [/\bsécurité solo\b/gi, 'seguridad solo'],
  [/\bétirement maximal\b/gi, 'estiramiento máximo'],
  [/\bétirement complet\b/gi, 'estiramiento completo'],
  [/\bextension complète\b/gi, 'extensión completa'],
  [/\btempo lent\b/gi, 'tempo lento'],
  [/\bsans élan\b/gi, 'sin impulso'],
  [/\bisolation pure\b/gi, 'aislamiento puro'],
  [/\bsans tricher\b/gi, 'sin trampa'],
  [/\blargeur d'épaules\b/gi, 'ancho de hombros'],
  [/\blégèrement plus large que les épaules\b/gi, 'algo más ancho que los hombros'],
  [/\bau-dessus de la tête\b/gi, 'por encima de la cabeza'],
  [/\bdans chaque bloc\b/gi, 'en cada bloque'],
  [/\bmax reps\b/gi, 'reps máximas'],
  [/\b15 sec repos\b/gi, '15 s descanso'],
  [/\b2-3 min de repos\b/gi, '2-3 min de descanso'],
  [/\bréglées?\b/gi, 'ajustadas'],
  [/\bderrière toi\b/gi, 'detrás de ti'],
  [/\bdans ton ventre\b/gi, 'al vientre'],
  [/\bvers ton visage\b/gi, 'hacia tu cara'],
  [/\bvers le front\b/gi, 'hacia la frente'],
  [/\bessentielle? pour la santé\b/gi, 'esencial para la salud'],
  [/\bExcellent finisher\b/gi, 'Excelente finisher'],
  [/\baspect bombé\b/gi, 'aspecto voluminoso'],
  [/\bdonne le relief\b/gi, 'da forma a la parte alta'],
  [/\bdonne du volume\b/gi, 'añade volumen'],
  [/\bsans douleur aux poignets\b/gi, 'sin dolor en muñecas'],
  [/\bcontrôlant\b/gi, 'controlando'],
  [/\bUNIQUEMENT\b/g, 'SOLO'],
  [/\bÉCARTANT\b/g, 'SEPARANDO'],
  [/\bVERS LES HANCHES\b/g, 'HACIA LAS CADERAS'],
  [/\bLE muscle\b/g, 'EL músculo'],
];

export function localizeNote(note: string): string {
  const lang = getLang();
  if (lang === 'fr') return note;
  const phrases = lang === 'en' ? FR_EN : FR_ES;
  let out = note;
  for (const [re, rep] of phrases) out = out.replace(re, rep);
  return out;
}
